version: 2
updates:
  - package-ecosystem: "pnpm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "17:00"
      timezone: "Asia/Kolkata"
    versioning-strategy: increase
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "17:00"
      timezone: "Asia/Kolkata"


